### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by zhiqiang21** [Lellansin/node-reload#1]
使用这个插件来做配置热更新的操作。下图是使用了插件后大概4-5，进程内存占用情况‘

![](http://7xs2tr.com1.z0.glb.clouddn.com/2017-04-16-%E5%86%85%E5%AD%98%E9%AB%98.png?)

刚开始以为是代码的问题，后来想想这样的内存异常也是就是出现在使用了这个插件以后出现的，就尝试卸载了这个插件，观察了几天，内存占用正常，所以这个插件还是在开发环境使用可以，线上环境，就不适合了。

![](http://7xs2tr.com1.z0.glb.clouddn.com/2017-04-16-124324.jpg?imageslim)

**Comment by Lellansin** [comment]
感谢测试

**Comment by Lellansin** [comment]
这模块确实有内存的问题

**Comment by Lellansin** [comment]
Fixed with v0.1.

Feel free to reopen.
